name: Story
description: Suggest an idea for this project
labels: ['Story']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest an idea!
  - type: textarea
    id: user-story
    attributes:
      label: Describe The User Story
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what you want to see!
      value: 'As a... I want... So that...'
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives You've Considered
      description: A clear and concise description of any alternative you've considered.
      placeholder: Tell us some alternatives!
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the story here.
    validations:
      required: false
  - type: textarea
    id: tasks
    attributes:
      label: Tasks For This Story
      description: Add any tasks that are required for this story.
      placeholder: Create a list of tasks!
      value: ' - [ ] https://github.com/moontreeapp/raven_front/issues/???'
    validations:
      required: false
  - type: textarea
    id: bugs
    attributes:
      label: Bugs For This Story
      description: Add any bugs that are replaced/fixed by this story.
      placeholder: Create a list of bugs!
      value: ' - [ ] https://github.com/moontreeapp/raven_front/issues/???'
    validations:
      required: false
