name: Task
description: Add a new task for this project
labels: ['Task']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to add a new task!
  - type: textarea
    id: task
    attributes:
      label: Describe The Task
      description: A clear and concise description of what needs to happen.
      placeholder: Tell us what you are going to do!
      # value: 'As a... I want... So that...'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the task here.
    validations:
      required: false
